export const ModelActionTypes = {
    SET_CURRENT_MODEL: 'SET_CURRENT_MODEL',
    SET_CURRENT_WHEEL: 'SET_CURRENT_WHEEL',
    SET_CURRENT_PRICOLOR: 'SET_CURRENT_PRICOLOR',
    SET_CURRENT_SECCOLOR: 'SET_CURRENT_SECCOLOR',
    SET_CURRENT_WINCOLOR: 'SET_CURRENT_WINCOLOR',
    SET_CURRENT_TIRECOLOR: 'SET_CURRENT_TIRECOLOR',
    SET_CURRENT_RIMCOLOR: 'SET_CURRENT_RIMCOLOR',
};