/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BallModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./models/ball/ball.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh 
        castShadow
        geometry={nodes.Ball_DefaultBall00.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/ball.glb')
